"use client";
import { useEffect, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { LayoutDashboard, Users, Route, LogOut, Plus, RefreshCw } from "lucide-react";

type Team={id:string,name:string,rating:number|null,players:{id:string,name:string}[]};
type Flight={id:string,round_no:number,name:string,start_hole:number,access_code:string,teams:{id:string,name:string}[]};

export default function AdminApp(){
 const [ok,setOk]=useState(false),[password,setPassword]=useState(""),[teams,setTeams]=useState<Team[]>([]),[flights,setFlights]=useState<Flight[]>([]),[round,setRound]=useState(1),[tab,setTab]=useState("overview"),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/admin");if(r.ok){const d=await r.json();setOk(true);setTeams(d.teams);setFlights(d.flights)}}
 useEffect(()=>{load()},[]);
 async function login(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/auth/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});if(r.ok)load();else setMessage("Pogrešna lozinka.")}
 async function addTeam(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"team",name:fd.get("name"),rating:Number(fd.get("rating"))||null,players:String(fd.get("players")).split(",").map(x=>x.trim()).filter(Boolean)})});if(r.ok){e.currentTarget.reset();load()}else setMessage("Ekipa mora imati točno četiri igrača.")}
 async function saveFlights(){const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"generateFlights",round})});setMessage(r.ok?"Flightovi su spremljeni.":"Nije moguće spremiti flightove.");load()}
 async function updateStart(flightId:string,startHole:number){const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"startHole",flightId,startHole})});setMessage(r.ok?"Početna staza je spremljena.":"Staza mora biti između 1 i 16.");if(r.ok)load()}
 if(!ok)return <main className="authPage"><form className="loginCard" onSubmit={login}><Image src="/lagoda-logo.jpg" alt="Lagoda" width={82} height={68}/><span className="eyebrow">ADMINISTRACIJA</span><h1>Dobrodošli</h1><p>Prijavite se za upravljanje turnirom.</p><label>Administratorska lozinka<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<div className="notice error">{message}</div>}<button className="btn">Prijava</button><Link href="/">← Povratak na rezultate</Link></form></main>;
 return <main className="adminLayout"><aside><div className="brand light"><Image src="/lagoda-logo.jpg" alt="Lagoda" width={48} height={48}/><span>TEAM <b>SHOWDOWN</b></span></div><nav><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}><LayoutDashboard/>Pregled</button><button className={tab==="teams"?"active":""} onClick={()=>setTab("teams")}><Users/>Ekipe</button><button className={tab==="flights"?"active":""} onClick={()=>setTab("flights")}><Route/>Flightovi</button></nav><button className="logout" onClick={()=>fetch("/api/auth/admin",{method:"DELETE"}).then(()=>location.reload())}><LogOut/>Odjava</button></aside><section className="adminMain"><header><div><span className="eyebrow">LAGODA TEAM SHOWDOWN 2026</span><h1>{tab==="teams"?"Prijavljene ekipe":tab==="flights"?"Flightovi i runde":"Kontrolni centar"}</h1></div><Link href="/" className="outline">Javni leaderboard ↗</Link></header>{message&&<div className="notice">{message}</div>}
 {tab==="overview"&&<div className="dashGrid"><article className="stat"><Users/><span>Prijavljene ekipe</span><b>{teams.length}</b></article><article className="stat"><Route/><span>Formirani flightovi</span><b>{flights.length}</b></article><article className="panel wide"><h2>Brzi početak</h2><ol><li>Provjerite ekipe i njihove članove.</li><li>Odaberite rundu i generirajte flightove.</li><li>Dodijelite početne staze prije početka runde.</li><li>Podijelite šifru zapisničarima.</li></ol></article></div>}
 {tab==="teams"&&<><form className="panel teamForm" onSubmit={addTeam}><h2><Plus/> Dodaj ekipu</h2><div className="formGrid"><label>Naziv ekipe<input name="name" required/></label><label>Rejting<input name="rating" type="number" step=".01"/></label><label className="span2">Četiri igrača, odvojena zarezom<input name="players" placeholder="Ana, Ivo, Mia, Luka" required/></label></div><button className="btn">Dodaj ekipu</button></form><div className="teamList">{teams.map((t,i)=><article key={t.id}><span className="rank">{i+1}</span><div><b>{t.name}</b><small>{t.players.map(p=>p.name).join(" · ")}</small></div><span>{t.rating?`Rejting ${t.rating}`:"Bez rejtinga"}</span></article>)}</div></>}
 {tab==="flights"&&<><div className="roundTabs">{[1,2,3].map(r=><button onClick={()=>setRound(r)} className={round===r?"active":""} key={r}>Runda {r}</button>)}</div><div className="panel flightPanel"><div><h2>Runda {round}</h2><p>Automatski rasporedi dvije ekipe po flightu. Početne staze mogu se promijeniti.</p></div><button className="btn" onClick={saveFlights}><RefreshCw/> Generiraj flightove</button></div><div className="flightGrid">{flights.filter(f=>f.round_no===round).map(f=><article key={f.id}><div><span className="eyebrow">{f.name}</span><h3>Početna staza {f.start_hole}</h3></div>{f.teams.map(t=><p key={t.id}>{t.name}</p>)}<div className="startEdit"><input id={`hole-${f.id}`} type="number" min="1" max="16" defaultValue={f.start_hole}/><button onClick={()=>updateStart(f.id,Number((document.getElementById(`hole-${f.id}`) as HTMLInputElement).value))}>Spremi stazu</button></div><small>Pristupna šifra</small><strong>{f.access_code}</strong></article>)}</div></>}
 </section></main>
}
