"use client";
import { useCallback, useEffect, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import QRCode from "qrcode";
import { LayoutDashboard, Users, Route, LogOut, Plus, RefreshCw, Target, Save, RotateCcw, AlertTriangle, Trash2, Printer } from "lucide-react";

type Team={id:string,name:string,rating:number|null,players:{id:string,name:string}[]};
type Flight={id:string,round_no:number,name:string,start_hole:number,access_code:string,teams:{id:string,name:string}[]};
type Hole={number:number,par:number};

export default function AdminApp(){
 const [ok,setOk]=useState(false),[password,setPassword]=useState(""),[teams,setTeams]=useState<Team[]>([]),[flights,setFlights]=useState<Flight[]>([]),[holes,setHoles]=useState<Hole[]>([]),[round,setRound]=useState(1),[tab,setTab]=useState("overview"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[qrCodes,setQrCodes]=useState<Record<string,string>>({});
 const applySnapshot=useCallback((d:{teams:Team[],flights:Flight[],holes:Hole[]})=>{setOk(true);setTeams(d.teams);setFlights(d.flights);setHoles(d.holes)},[]);
 const load=useCallback(async()=>{const r=await fetch("/api/admin");if(r.ok)applySnapshot(await r.json())},[applySnapshot]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{const roundFlights=flights.filter(f=>f.round_no===round);if(!roundFlights.length)return;let cancelled=false;Promise.all(roundFlights.map(async f=>[f.id,await QRCode.toDataURL(`${window.location.origin}/scoring`,{width:260,margin:1,errorCorrectionLevel:"M"})] as const)).then(entries=>{if(!cancelled)setQrCodes(Object.fromEntries(entries))});return()=>{cancelled=true}},[flights,round]);
 async function login(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/auth/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});if(r.ok)load();else setMessage("Pogrešna lozinka.")}
 async function addTeam(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=e.currentTarget,fd=new FormData(form),players=[1,2,3,4].map(n=>String(fd.get(`player${n}`)||"").trim());const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"team",name:String(fd.get("name")||"").trim(),rating:Number(fd.get("rating"))||null,players})});setBusy(false);if(r.ok){applySnapshot(await r.json());form.reset();setMessage("Ekipa je dodana i odmah prikazana u listi.")}else{const d=await r.json().catch(()=>({}));setMessage(d.error==="team already exists"?"Ekipa s tim nazivom već postoji.":"Unesite naziv ekipe i sva četiri igrača.")}}
 async function deleteTeam(team:Team){if(!window.confirm(`Trajno izbrisati ekipu “${team.name}”? Bit će uklonjeni i njezini rezultati te dodjele flightovima.`))return;setBusy(true);const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"deleteTeam",teamId:team.id,confirm:team.name})});setBusy(false);if(r.ok){applySnapshot(await r.json());setMessage(`Ekipa “${team.name}” je izbrisana.`)}else setMessage("Brisanje ekipe nije uspjelo.")}
 async function saveFlights(){setBusy(true);const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"generateFlights",round})});setBusy(false);if(r.ok){applySnapshot(await r.json());setMessage("Flightovi su nasumično generirani.")}else setMessage("Nije moguće generirati flightove.")}
 function updateFlightTeam(flightId:string,position:number,teamId:string){setFlights(current=>current.map(f=>{if(f.id!==flightId)return f;const next=[...f.teams],team=teams.find(t=>t.id===teamId);if(team)next[position]={id:team.id,name:team.name};else if(position===1)next.splice(1,1);return {...f,teams:next}}))}
 async function saveFlightAssignments(){const selected=flights.filter(f=>f.round_no===round).map(f=>({flightId:f.id,teamIds:f.teams.map(t=>t.id).filter(Boolean)}));setBusy(true);const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"saveFlightAssignments",round,flights:selected})});setBusy(false);if(r.ok){applySnapshot(await r.json());setMessage("Promjene ekipa u flightovima su spremljene.")}else{const d=await r.json().catch(()=>({}));setMessage(d.error==="duplicate team"?"Ista ekipa ne može biti u dva flighta iste runde.":"Svaki flight mora imati jednu ili dvije valjane ekipe.")}}
 async function updateStart(flightId:string,startHole:number){const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"startHole",flightId,startHole})});setMessage(r.ok?"Početna staza je spremljena.":"Staza mora biti između 1 i 16.");if(r.ok)load()}
 async function saveHoles(){setBusy(true);const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"holes",holes})});setBusy(false);setMessage(r.ok?"Parovi svih staza su spremljeni.":"Par mora biti između 1 i 9.");if(r.ok)load()}
 async function resetTournament(){if(!window.confirm("Reset će trajno obrisati sve rezultate i flightove iz sve tri runde. Ekipe, igrači i parovi staza ostat će sačuvani. Želite li nastaviti?"))return;setBusy(true);const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"resetTournament",confirm:"RESET"})});setBusy(false);setMessage(r.ok?"Turnir je resetiran. Rezultati i flightovi su obrisani.":"Resetiranje nije uspjelo.");if(r.ok)load()}
 if(!ok)return <main className="authPage"><form className="loginCard" onSubmit={login}><Image src="/lagoda-logo.jpg" alt="Lagoda" width={82} height={68}/><span className="eyebrow">ADMINISTRACIJA</span><h1>Dobrodošli</h1><p>Prijavite se za upravljanje turnirom.</p><label>Administratorska lozinka<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<div className="notice error">{message}</div>}<button className="btn">Prijava</button><Link href="/">← Povratak na rezultate</Link></form></main>;
 return <main className="adminLayout"><aside><div className="brand light"><Image src="/lagoda-logo.jpg" alt="Lagoda" width={48} height={48}/><span>TEAM <b>SHOWDOWN</b></span></div><nav><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}><LayoutDashboard/>Pregled</button><button className={tab==="teams"?"active":""} onClick={()=>setTab("teams")}><Users/>Ekipe</button><button className={tab==="course"?"active":""} onClick={()=>setTab("course")}><Target/>Staze i par</button><button className={tab==="flights"?"active":""} onClick={()=>setTab("flights")}><Route/>Flightovi</button></nav><button className="logout" onClick={()=>fetch("/api/auth/admin",{method:"DELETE"}).then(()=>location.reload())}><LogOut/>Odjava</button></aside><section className="adminMain"><header><div><span className="eyebrow">LAGODA TEAM SHOWDOWN 2026</span><h1>{tab==="teams"?"Prijavljene ekipe":tab==="flights"?"Flightovi i runde":tab==="course"?"Staze i par":"Kontrolni centar"}</h1></div><Link href="/" className="outline">Javni leaderboard ↗</Link></header>{message&&<div className="notice">{message}</div>}
 {tab==="overview"&&<div className="dashGrid"><article className="stat"><Users/><span>Prijavljene ekipe</span><b>{teams.length}</b></article><article className="stat"><Route/><span>Formirani flightovi</span><b>{flights.length}</b></article><article className="panel wide"><h2>Brzi početak</h2><ol><li>Provjerite ekipe i njihove članove.</li><li>Postavite par za svaku stazu.</li><li>Odaberite rundu i generirajte flightove.</li><li>Dodijelite početne staze i podijelite šifre.</li></ol></article><article className="panel wide dangerPanel"><div><AlertTriangle/><div><h2>Resetiranje turnira</h2><p>Briše rezultate i flightove iz sve tri runde. Ekipe, igrači i parovi staza ostaju sačuvani.</p></div></div><button disabled={busy} onClick={resetTournament}><RotateCcw/> Resetiraj turnir</button></article></div>}
 {tab==="teams"&&<><form className="panel teamForm" onSubmit={addTeam}><h2><Plus/> Dodaj ekipu</h2><div className="formGrid"><label>Naziv ekipe<input name="name" placeholder="Naziv ekipe" required/></label><label>Rejting<input name="rating" type="number" step=".01" placeholder="Opcionalno"/></label><div className="playerFields span2">{[1,2,3,4].map(n=><label key={n}>Igrač {n}<input name={`player${n}`} placeholder={`Ime igrača ${n}`} required/></label>)}</div></div><button className="btn" disabled={busy}>{busy?"Dodavanje…":"Dodaj ekipu"}</button></form><div className="teamList">{teams.map((t,i)=><article key={t.id}><span className="rank">{i+1}</span><div><b>{t.name}</b><small>{t.players.map(p=>p.name).join(" · ")}</small></div><div className="teamActions"><span>{t.rating?`Rejting ${t.rating}`:"Bez rejtinga"}</span><button disabled={busy} onClick={()=>deleteTeam(t)} aria-label={`Izbriši ekipu ${t.name}`}><Trash2/> Izbriši</button></div></article>)}</div></>}
 {tab==="course"&&<><div className="panel courseIntro"><div><h2>Parovi staza</h2><p>Promjena se primjenjuje na scorecard i izračun rezultata u odnosu na par.</p></div><button className="btn" disabled={busy} onClick={saveHoles}><Save/> {busy?"Spremanje…":"Spremi parove"}</button></div><div className="holesGrid">{holes.map(h=><label key={h.number} style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:16,background:"#fff",border:"1px solid var(--line)",borderRadius:12,padding:"14px 16px"}}><strong style={{fontFamily:"var(--font-display)",fontSize:20,textTransform:"uppercase",color:"var(--green-dark)"}}>Staza {h.number}</strong><span style={{display:"flex",alignItems:"center",gap:8,fontSize:11,fontWeight:900,color:"var(--green)"}}>PAR <input aria-label={`Par staze ${h.number}`} style={{width:52,border:"1px solid var(--line)",borderRadius:8,padding:8,textAlign:"center",fontWeight:900}} type="number" min="1" max="9" value={h.par} onChange={e=>setHoles(current=>current.map(item=>item.number===h.number?{...item,par:Number(e.target.value)}:item))}/></span></label>)}</div></>}
 {tab==="flights"&&<><div className="roundTabs">{[1,2,3].map(r=><button onClick={()=>setRound(r)} className={round===r?"active":""} key={r}>Runda {r}</button>)}</div><div className="panel flightPanel"><div><h2>Runda {round}</h2><p>Ekipe se raspoređuju nasumično, a zatim ih možete promijeniti i spremiti.</p></div><div className="flightActions">{flights.some(f=>f.round_no===round)&&<button className="outline" onClick={()=>window.print()}><Printer/> Ispiši flightove</button>}<button className="outline" disabled={busy} onClick={saveFlightAssignments}><Save/> Spremi promjene</button><button className="btn" disabled={busy} onClick={saveFlights}><RefreshCw/> Generiraj flightove</button></div></div><div className="flightGrid">{flights.filter(f=>f.round_no===round).map(f=><article key={f.id}><div><span className="eyebrow">{f.name}</span><h3>Početna staza {f.start_hole}</h3></div><div className="flightTeamSelects"><label>Ekipa 1<select value={f.teams[0]?.id||""} onChange={e=>updateFlightTeam(f.id,0,e.target.value)}><option value="" disabled>Odaberite ekipu</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Ekipa 2 <small>(opcionalno)</small><select value={f.teams[1]?.id||""} onChange={e=>updateFlightTeam(f.id,1,e.target.value)}><option value="">Bez druge ekipe</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div><div className="startEdit"><input id={`hole-${f.id}`} type="number" min="1" max="16" defaultValue={f.start_hole}/><button onClick={()=>updateStart(f.id,Number((document.getElementById(`hole-${f.id}`) as HTMLInputElement).value))}>Spremi stazu</button></div><small>Pristupna šifra</small><strong>{f.access_code}</strong></article>)}</div><section className="printSheet"><header><Image src="/lagoda-logo.jpg" alt="Lagoda" width={58} height={58}/><div><span>LAGODA TEAM SHOWDOWN 2026</span><h1>Flightovi — Runda {round}</h1></div></header><div className="printFlightGrid">{flights.filter(f=>f.round_no===round).map(f=><article key={f.id}><div className="printFlightInfo"><span>{f.name}</span><h2>Početna staza {f.start_hole}</h2><ul>{f.teams.map(t=><li key={t.id}>{t.name}</li>)}</ul><small>Pristupna šifra</small><strong>{f.access_code}</strong></div>{qrCodes[f.id]&&<Image src={qrCodes[f.id]} alt={`QR kod za ${f.name}`} width={130} height={130} unoptimized/>}<p>Skenirajte QR kod, provjerite šifru i otvorite scorecard.</p></article>)}</div></section></>}
 </section></main>
}
