"use client";
import { useCallback, useEffect, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import QRCode from "qrcode";
import { LayoutDashboard, Users, Route, LogOut, Plus, RefreshCw, Target, Save, RotateCcw, AlertTriangle, Trash2, Printer, Languages } from "lucide-react";

type Team={id:string,name:string,rating:number|null,players:{id:string,name:string}[]};
type Flight={id:string,round_no:number,name:string,start_hole:number,access_code:string,teams:{id:string,name:string}[]};
type Hole={number:number,par:number};
type Language="hr"|"en";

const copy={
 hr:{administration:"ADMINISTRACIJA",welcome:"Dobrodošli",loginIntro:"Prijavite se za upravljanje turnirom.",adminPassword:"Administratorska lozinka",login:"Prijava",back:"← Povratak na rezultate",wrongPassword:"Pogrešna lozinka.",overview:"Pregled",teams:"Ekipe",course:"Staze i par",flights:"Flightovi",logout:"Odjava",registeredTeams:"Prijavljene ekipe",flightsRounds:"Flightovi i runde",controlCenter:"Kontrolni centar",leaderboard:"Javni leaderboard ↗",formedFlights:"Formirani flightovi",quickStart:"Brzi početak",steps:["Provjerite ekipe i njihove članove.","Postavite par za svaku stazu.","Odaberite rundu i generirajte flightove.","Dodijelite početne staze i podijelite šifre."],resetTitle:"Resetiranje turnira",resetInfo:"Briše rezultate i flightove iz sve tri runde. Ekipe, igrači i parovi staza ostaju sačuvani.",reset:"Resetiraj turnir",addTeam:"Dodaj ekipu",teamName:"Naziv ekipe",rating:"Rejting",optional:"Opcionalno",player:"Igrač",playerName:"Ime igrača",adding:"Dodavanje…",noRating:"Bez rejtinga",delete:"Izbriši",holesPar:"Parovi staza",holesInfo:"Promjena se primjenjuje na scorecard i izračun rezultata u odnosu na par.",saving:"Spremanje…",savePars:"Spremi parove",hole:"Staza",round:"Runda",flightInfo:"Ekipe se raspoređuju nasumično, a zatim ih možete promijeniti i spremiti.",printFlights:"Ispiši flightove",saveChanges:"Spremi promjene",generate:"Generiraj flightove",startHole:"Početna staza",team1:"Ekipa 1",team2:"Ekipa 2",selectTeam:"Odaberite ekipu",noSecondTeam:"Bez druge ekipe",saveHole:"Spremi stazu",accessCode:"Pristupna šifra",scan:"Skenirajte QR kod, upišite šifru i otvorite scorecard.",language:"Jezik",teamAdded:"Ekipa je dodana i odmah prikazana u listi.",teamExists:"Ekipa s tim nazivom već postoji.",fourPlayers:"Unesite naziv ekipe i sva četiri igrača.",deleteFailed:"Brisanje ekipe nije uspjelo.",generated:"Flightovi su nasumično generirani.",generateFailed:"Nije moguće generirati flightove.",assignmentsSaved:"Promjene ekipa u flightovima su spremljene.",duplicate:"Ista ekipa ne može biti u dva flighta iste runde.",invalidFlights:"Svaki flight mora imati jednu ili dvije valjane ekipe.",holeSaved:"Početna staza je spremljena.",invalidHole:"Staza mora biti između 1 i 16.",parsSaved:"Parovi svih staza su spremljeni.",invalidPar:"Par mora biti između 1 i 9.",resetDone:"Turnir je resetiran. Rezultati i flightovi su obrisani.",resetFailed:"Resetiranje nije uspjelo."},
 en:{administration:"ADMINISTRATION",welcome:"Welcome",loginIntro:"Sign in to manage the tournament.",adminPassword:"Administrator password",login:"Sign in",back:"← Back to results",wrongPassword:"Incorrect password.",overview:"Overview",teams:"Teams",course:"Holes and par",flights:"Flights",logout:"Sign out",registeredTeams:"Registered teams",flightsRounds:"Flights and rounds",controlCenter:"Control center",leaderboard:"Public leaderboard ↗",formedFlights:"Created flights",quickStart:"Quick start",steps:["Review the teams and their players.","Set the par for each hole.","Select a round and generate flights.","Assign starting holes and share the access codes."],resetTitle:"Reset tournament",resetInfo:"Deletes scores and flights from all three rounds. Teams, players and hole pars remain saved.",reset:"Reset tournament",addTeam:"Add team",teamName:"Team name",rating:"Rating",optional:"Optional",player:"Player",playerName:"Player name",adding:"Adding…",noRating:"No rating",delete:"Delete",holesPar:"Hole pars",holesInfo:"Changes are applied to the scorecard and score-to-par calculation.",saving:"Saving…",savePars:"Save pars",hole:"Hole",round:"Round",flightInfo:"Teams are assigned randomly, then you can change and save them.",printFlights:"Print flights",saveChanges:"Save changes",generate:"Generate flights",startHole:"Starting hole",team1:"Team 1",team2:"Team 2",selectTeam:"Select a team",noSecondTeam:"No second team",saveHole:"Save hole",accessCode:"Access code",scan:"Scan the QR code, enter the access code and open the scorecard.",language:"Language",teamAdded:"The team was added and is now shown in the list.",teamExists:"A team with that name already exists.",fourPlayers:"Enter the team name and all four players.",deleteFailed:"The team could not be deleted.",generated:"Flights were generated randomly.",generateFailed:"Flights could not be generated.",assignmentsSaved:"Flight team changes were saved.",duplicate:"A team cannot be assigned to two flights in the same round.",invalidFlights:"Each flight must have one or two valid teams.",holeSaved:"The starting hole was saved.",invalidHole:"The hole must be between 1 and 16.",parsSaved:"All hole pars were saved.",invalidPar:"Par must be between 1 and 9.",resetDone:"The tournament was reset. Scores and flights were deleted.",resetFailed:"The tournament could not be reset."}
} as const;

export default function AdminApp(){
 const [ok,setOk]=useState(false),[password,setPassword]=useState(""),[teams,setTeams]=useState<Team[]>([]),[flights,setFlights]=useState<Flight[]>([]),[holes,setHoles]=useState<Hole[]>([]),[round,setRound]=useState(1),[tab,setTab]=useState("overview"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[qrCodes,setQrCodes]=useState<Record<string,string>>({}),[language,setLanguage]=useState<Language>("hr");
 const t=copy[language];
 const applySnapshot=useCallback((d:{teams:Team[],flights:Flight[],holes:Hole[]})=>{setOk(true);setTeams(d.teams);setFlights(d.flights);setHoles(d.holes)},[]);
 const load=useCallback(async()=>{const r=await fetch("/api/admin");if(r.ok)applySnapshot(await r.json())},[applySnapshot]);
 useEffect(()=>{load();const saved=localStorage.getItem("lts-language");if(saved==="hr"||saved==="en")setLanguage(saved)},[load]);
 useEffect(()=>{const roundFlights=flights.filter(f=>f.round_no===round);if(!roundFlights.length)return;let cancelled=false;Promise.all(roundFlights.map(async f=>[f.id,await QRCode.toDataURL(`${window.location.origin}/scoring`,{width:260,margin:1,errorCorrectionLevel:"M"})] as const)).then(entries=>{if(!cancelled)setQrCodes(Object.fromEntries(entries))});return()=>{cancelled=true}},[flights,round]);
 function switchLanguage(next:Language){setLanguage(next);localStorage.setItem("lts-language",next);document.documentElement.lang=next;setMessage("")}
 async function login(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/auth/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});if(r.ok)load();else setMessage(t.wrongPassword)}
 async function addTeam(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=e.currentTarget,fd=new FormData(form),players=[1,2,3,4].map(n=>String(fd.get(`player${n}`)||"").trim());const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"team",name:String(fd.get("name")||"").trim(),rating:Number(fd.get("rating"))||null,players})});setBusy(false);if(r.ok){applySnapshot(await r.json());form.reset();setMessage(t.teamAdded)}else{const d=await r.json().catch(()=>({}));setMessage(d.error==="team already exists"?t.teamExists:t.fourPlayers)}}
 async function deleteTeam(team:Team){const question=language==="hr"?`Trajno izbrisati ekipu “${team.name}”? Bit će uklonjeni i njezini rezultati te dodjele flightovima.`:`Permanently delete “${team.name}”? Its scores and flight assignments will also be removed.`;if(!window.confirm(question))return;setBusy(true);const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"deleteTeam",teamId:team.id,confirm:team.name})});setBusy(false);if(r.ok){applySnapshot(await r.json());setMessage(language==="hr"?`Ekipa “${team.name}” je izbrisana.`:`Team “${team.name}” was deleted.`)}else setMessage(t.deleteFailed)}
 async function saveFlights(){setBusy(true);const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"generateFlights",round})});setBusy(false);if(r.ok){applySnapshot(await r.json());setMessage(t.generated)}else setMessage(t.generateFailed)}
 function updateFlightTeam(flightId:string,position:number,teamId:string){setFlights(current=>current.map(f=>{if(f.id!==flightId)return f;const next=[...f.teams],team=teams.find(item=>item.id===teamId);if(team)next[position]={id:team.id,name:team.name};else if(position===1)next.splice(1,1);return {...f,teams:next}}))}
 async function saveFlightAssignments(){const selected=flights.filter(f=>f.round_no===round).map(f=>({flightId:f.id,teamIds:f.teams.map(team=>team.id).filter(Boolean)}));setBusy(true);const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"saveFlightAssignments",round,flights:selected})});setBusy(false);if(r.ok){applySnapshot(await r.json());setMessage(t.assignmentsSaved)}else{const d=await r.json().catch(()=>({}));setMessage(d.error==="duplicate team"?t.duplicate:t.invalidFlights)}}
 async function updateStart(flightId:string,startHole:number){const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"startHole",flightId,startHole})});setMessage(r.ok?t.holeSaved:t.invalidHole);if(r.ok)load()}
 async function saveHoles(){setBusy(true);const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"holes",holes})});setBusy(false);setMessage(r.ok?t.parsSaved:t.invalidPar);if(r.ok)load()}
 async function resetTournament(){const question=language==="hr"?"Reset će trajno obrisati sve rezultate i flightove iz sve tri runde. Ekipe, igrači i parovi staza ostat će sačuvani. Želite li nastaviti?":"Reset will permanently delete all scores and flights from all three rounds. Teams, players and hole pars will remain saved. Do you want to continue?";if(!window.confirm(question))return;setBusy(true);const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"resetTournament",confirm:"RESET"})});setBusy(false);setMessage(r.ok?t.resetDone:t.resetFailed);if(r.ok)load()}
 const languagePicker=<label className="languageSelect"><Languages size={16}/><span className="srOnly">{t.language}</span><select value={language} onChange={e=>switchLanguage(e.target.value as Language)} aria-label={t.language}><option value="hr">HR</option><option value="en">EN</option></select></label>;
 if(!ok)return <main className="authPage"><form className="loginCard" onSubmit={login}><div className="adminLoginTop"><Image src="/lagoda-logo.jpg" alt="Lagoda" width={82} height={68}/>{languagePicker}</div><span className="eyebrow">{t.administration}</span><h1>{t.welcome}</h1><p>{t.loginIntro}</p><label>{t.adminPassword}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<div className="notice error">{message}</div>}<button className="btn">{t.login}</button><Link href="/">{t.back}</Link></form></main>;
 const pageTitle=tab==="teams"?t.registeredTeams:tab==="flights"?t.flightsRounds:tab==="course"?t.course:t.controlCenter;
 const roundFlights=flights.filter(f=>f.round_no===round);
 return <main className="adminLayout"><aside><div className="brand light"><Image src="/lagoda-logo.jpg" alt="Lagoda" width={48} height={48}/><span>TEAM <b>SHOWDOWN</b></span></div><nav><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}><LayoutDashboard/>{t.overview}</button><button className={tab==="teams"?"active":""} onClick={()=>setTab("teams")}><Users/>{t.teams}</button><button className={tab==="course"?"active":""} onClick={()=>setTab("course")}><Target/>{t.course}</button><button className={tab==="flights"?"active":""} onClick={()=>setTab("flights")}><Route/>{t.flights}</button></nav><button className="logout" onClick={()=>fetch("/api/auth/admin",{method:"DELETE"}).then(()=>location.reload())}><LogOut/>{t.logout}</button></aside><section className="adminMain"><header><div><span className="eyebrow">LAGODA TEAM SHOWDOWN 2026</span><h1>{pageTitle}</h1></div><div className="adminHeaderActions">{languagePicker}<Link href="/" className="outline">{t.leaderboard}</Link></div></header>{message&&<div className="notice">{message}</div>}
 {tab==="overview"&&<div className="dashGrid"><article className="stat"><Users/><span>{t.registeredTeams}</span><b>{teams.length}</b></article><article className="stat"><Route/><span>{t.formedFlights}</span><b>{flights.length}</b></article><article className="panel wide"><h2>{t.quickStart}</h2><ol>{t.steps.map(step=><li key={step}>{step}</li>)}</ol></article><article className="panel wide dangerPanel"><div><AlertTriangle/><div><h2>{t.resetTitle}</h2><p>{t.resetInfo}</p></div></div><button disabled={busy} onClick={resetTournament}><RotateCcw/> {t.reset}</button></article></div>}
 {tab==="teams"&&<><form className="panel teamForm" onSubmit={addTeam}><h2><Plus/> {t.addTeam}</h2><div className="formGrid"><label>{t.teamName}<input name="name" placeholder={t.teamName} required/></label><label>{t.rating}<input name="rating" type="number" step=".01" placeholder={t.optional}/></label><div className="playerFields span2">{[1,2,3,4].map(n=><label key={n}>{t.player} {n}<input name={`player${n}`} placeholder={`${t.playerName} ${n}`} required/></label>)}</div></div><button className="btn" disabled={busy}>{busy?t.adding:t.addTeam}</button></form><div className="teamList">{teams.map((team,i)=><article key={team.id}><span className="rank">{i+1}</span><div><b>{team.name}</b><small>{team.players.map(player=>player.name).join(" · ")}</small></div><div className="teamActions"><span>{team.rating?`${t.rating} ${team.rating}`:t.noRating}</span><button disabled={busy} onClick={()=>deleteTeam(team)} aria-label={`${t.delete} ${team.name}`}><Trash2/> {t.delete}</button></div></article>)}</div></>}
 {tab==="course"&&<><div className="panel courseIntro"><div><h2>{t.holesPar}</h2><p>{t.holesInfo}</p></div><button className="btn" disabled={busy} onClick={saveHoles}><Save/> {busy?t.saving:t.savePars}</button></div><div className="holesGrid">{holes.map(h=><label key={h.number}><strong>{t.hole} {h.number}</strong><span>PAR <input aria-label={`Par ${h.number}`} type="number" min="1" max="9" value={h.par} onChange={e=>setHoles(current=>current.map(item=>item.number===h.number?{...item,par:Number(e.target.value)}:item))}/></span></label>)}</div></>}
 {tab==="flights"&&<><div className="roundTabs">{[1,2,3].map(r=><button onClick={()=>setRound(r)} className={round===r?"active":""} key={r}>{t.round} {r}</button>)}</div><div className="panel flightPanel"><div><h2>{t.round} {round}</h2><p>{t.flightInfo}</p></div><div className="flightActions">{!!roundFlights.length&&<button className="outline" onClick={()=>window.print()}><Printer/> {t.printFlights}</button>}<button className="outline" disabled={busy} onClick={saveFlightAssignments}><Save/> {t.saveChanges}</button><button className="btn" disabled={busy} onClick={saveFlights}><RefreshCw/> {t.generate}</button></div></div><div className="flightGrid">{roundFlights.map(f=><article key={f.id}><div><span className="eyebrow">{f.name}</span><h3>{t.startHole} {f.start_hole}</h3></div><div className="flightTeamSelects"><label>{t.team1}<select value={f.teams[0]?.id||""} onChange={e=>updateFlightTeam(f.id,0,e.target.value)}><option value="" disabled>{t.selectTeam}</option>{teams.map(team=><option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label>{t.team2} <small>({t.optional.toLowerCase()})</small><select value={f.teams[1]?.id||""} onChange={e=>updateFlightTeam(f.id,1,e.target.value)}><option value="">{t.noSecondTeam}</option>{teams.map(team=><option key={team.id} value={team.id}>{team.name}</option>)}</select></label></div><div className="startEdit"><input id={`hole-${f.id}`} type="number" min="1" max="16" defaultValue={f.start_hole}/><button onClick={()=>updateStart(f.id,Number((document.getElementById(`hole-${f.id}`) as HTMLInputElement).value))}>{t.saveHole}</button></div><small>{t.accessCode}</small><strong>{f.access_code}</strong></article>)}</div><section className="printSheet"><header><Image src="/lagoda-logo.jpg" alt="Lagoda" width={58} height={58}/><div><span>LAGODA TEAM SHOWDOWN 2026</span><h1>{t.flights} — {t.round} {round}</h1></div></header><div className="printFlightGrid">{roundFlights.map(f=><article key={f.id}><div className="printFlightInfo"><span>{f.name}</span><h2>{t.startHole} {f.start_hole}</h2><ul>{f.teams.map(team=><li key={team.id}>{team.name}</li>)}</ul><small>{t.accessCode}</small><strong>{f.access_code}</strong></div>{qrCodes[f.id]&&<Image src={qrCodes[f.id]} alt={`QR ${f.name}`} width={130} height={130} unoptimized/>}<p>{t.scan}</p></article>)}</div></section></>}
 </section></main>
}
