"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { Check, ChevronLeft, ChevronRight, Wifi, WifiOff, Languages } from "lucide-react";

type Score={team_id:string,hole_no:number,strokes:number,opener_id:string};
type FlightData={flight:{id:string,name:string,round_no:number,start_hole:number},teams:{id:string,name:string,players:{id:string,name:string}[]}[],scores:Score[],holes:{number:number,par:number}[]};
type Draft={openerId:string,strokes:number};
type PendingScore={teamId:string,hole:number,openerId:string,strokes:number};
type Language="hr"|"en";
const copy={
  hr:{recorder:"ZAPISNIČAR",flightLogin:"Prijava flighta",loginIntro:"Unesite šifru koju ste dobili od organizatora.",flightCode:"Šifra flighta",open:"Otvori scorecard",back:"← Povratak na leaderboard",invalidCode:"Šifra nije ispravna ili runda nije aktivna.",firstConnection:"Za otvaranje scorecarda prvi put potrebna je internetska veza.",localSynced:"Lokalno spremljeni rezultati su sinkronizirani.",synced:"Rezultati su sinkronizirani.",openerLimit:"Igrač već ima četiri početna bacanja. Ispravite lokalno spremljeni rezultat.",savedForRetry:"Rezultati su sačuvani na uređaju i pokušat će se ponovno poslati.",offlineSafe:"Nema veze. Rezultati su sigurno spremljeni na ovom uređaju.",previousSaved:"Rezultati prethodne staze automatski su spremljeni.",round:"Runda",syncing:"Sinkronizacija…",local:"lokalno spremljeno",waiting:"čeka slanje",hole:"STAZA",previousHole:"Prethodna staza",nextHole:"Sljedeća staza",finish:"Završi rundu",team:"EKIPA",saved:"Spremljeno",opener:"Početno bacanje",strokes:"Broj bacanja",openerRound:"Početna bacanja u rundi",language:"Jezik",results:"Rezultati flighta",resultsIntro:"Pregled svih rezultata ove runde.",total:"Ukupno",toPar:"± Par",editAgain:"Ponovno prođi i uredi rezultate",completeAll:"Nedostaju rezultati na jednoj ili više staza. Vratite se i unesite ih prije završetka."},
  en:{recorder:"SCOREKEEPER",flightLogin:"Flight login",loginIntro:"Enter the access code provided by the organizer.",flightCode:"Flight access code",open:"Open scorecard",back:"← Back to leaderboard",invalidCode:"The code is incorrect or the round is not active.",firstConnection:"An internet connection is required when opening the scorecard for the first time.",localSynced:"Locally saved scores have been synchronized.",synced:"Scores have been synchronized.",openerLimit:"This player already has four opening throws. Correct the locally saved score.",savedForRetry:"Scores are saved on this device and will be sent again automatically.",offlineSafe:"No connection. Scores are safely saved on this device.",previousSaved:"Scores from the previous hole were saved automatically.",round:"Round",syncing:"Synchronizing…",local:"saved locally",waiting:"waiting to send",hole:"HOLE",previousHole:"Previous hole",nextHole:"Next hole",finish:"Finish round",team:"TEAM",saved:"Saved",opener:"Opening throw",strokes:"Number of throws",openerRound:"Opening throws in this round",language:"Language",results:"Flight results",resultsIntro:"Review all scores from this round.",total:"Total",toPar:"± Par",editAgain:"Review and edit scores again",completeAll:"Scores are missing on one or more holes. Go back and enter them before finishing."}
} as const;

export default function ScoringApp(){
  const [code,setCode]=useState(""),[data,setData]=useState<FlightData|null>(null),[position,setPosition]=useState(0),[showResults,setShowResults]=useState(false),[msg,setMsg]=useState(""),[drafts,setDrafts]=useState<Record<string,Draft>>({}),[saving,setSaving]=useState(false),[online,setOnline]=useState(true),[pendingCount,setPendingCount]=useState(0),[language,setLanguage]=useState<Language>("hr");
  const t=copy[language];
  const hole=((data?.flight.start_hole||1)-1+position)%16+1;
  const syncing=useRef(false),syncLatest=useRef<()=>void>(()=>{});
  const key=(teamId:string,holeNo:number)=>`${teamId}:${holeNo}`;
  const storageKey=(flightId:string)=>`lts-offline-scores:${flightId}`;

  function readPending(flightId:string):PendingScore[]{try{const value=JSON.parse(localStorage.getItem(storageKey(flightId))||"[]");return Array.isArray(value)?value:[]}catch{return []}}
  function writePending(flightId:string,scores:PendingScore[]){const current=readPending(flightId);for(const score of scores){const index=current.findIndex(item=>item.teamId===score.teamId&&item.hole===score.hole);if(index>=0)current[index]=score;else current.push(score)}localStorage.setItem(storageKey(flightId),JSON.stringify(current));setPendingCount(current.length)}
  function clearConfirmed(flightId:string,sent:PendingScore[]){const current=readPending(flightId).filter(item=>!sent.some(saved=>saved.teamId===item.teamId&&saved.hole===item.hole&&saved.openerId===item.openerId&&saved.strokes===item.strokes));if(current.length)localStorage.setItem(storageKey(flightId),JSON.stringify(current));else localStorage.removeItem(storageKey(flightId));setPendingCount(current.length)}

  useEffect(()=>{const saved=localStorage.getItem("lts-language");if(saved==="hr"||saved==="en"){setLanguage(saved);document.documentElement.lang=saved}setOnline(navigator.onLine);const connected=()=>{setOnline(true);syncLatest.current()},disconnected=()=>setOnline(false);window.addEventListener("online",connected);window.addEventListener("offline",disconnected);return()=>{window.removeEventListener("online",connected);window.removeEventListener("offline",disconnected)}},[]);
  function switchLanguage(next:Language){setLanguage(next);localStorage.setItem("lts-language",next);document.documentElement.lang=next;setMsg("")}

  async function login(e:React.FormEvent){e.preventDefault();try{const r=await fetch("/api/scoring",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"login",code})});if(r.ok){const d:FlightData=await r.json(),pending=readPending(d.flight.id),restored:Record<string,Draft>={};pending.forEach(score=>{restored[key(score.teamId,score.hole)]={openerId:score.openerId,strokes:score.strokes}});setDrafts(restored);setPendingCount(pending.length);setData(d);setPosition(0);setShowResults(false);setTimeout(()=>syncPending(t.localSynced,d),0)}else setMsg(t.invalidCode)}catch{setMsg(t.firstConnection)}}
  function updateDraft(teamId:string,value:Draft){setDrafts(current=>({...current,[key(teamId,hole)]:value}));if(data&&value.openerId){writePending(data.flight.id,[{teamId,hole,openerId:value.openerId,strokes:value.strokes}]);setTimeout(()=>syncLatest.current(),0)}}
  function draftFor(teamId:string,holeNo:number):Draft|undefined{const draft=drafts[key(teamId,holeNo)];if(draft)return draft;const saved=data?.scores.find(s=>s.team_id===teamId&&s.hole_no===holeNo);return saved?{openerId:saved.opener_id,strokes:saved.strokes}:undefined}
  function currentDraft(teamId:string){return draftFor(teamId,hole)}
  function openerCounts(teamId:string){const byHole=new Map<number,string>();data?.scores.filter(s=>s.team_id===teamId).forEach(s=>byHole.set(s.hole_no,s.opener_id));Object.entries(drafts).filter(([draftKey])=>draftKey.startsWith(`${teamId}:`)).forEach(([draftKey,draft])=>{if(draft.openerId)byHole.set(Number(draftKey.split(":")[1]),draft.openerId)});const counts:Record<string,number>={};byHole.forEach(openerId=>{counts[openerId]=(counts[openerId]||0)+1});return counts}

  async function syncPending(message:string=t.synced,flightData:FlightData|null=data){
    if(!flightData||syncing.current)return false;const scores=readPending(flightData.flight.id);setPendingCount(scores.length);if(!scores.length)return true;
    syncing.current=true;setSaving(true);
    try{const r=await fetch("/api/scoring",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"scores",scores})});if(r.ok){setData(await r.json());clearConfirmed(flightData.flight.id,scores);setOnline(true);setMsg(message);return true}const error=await r.json().catch(()=>({}));setMsg(error.error==="opener limit reached"?t.openerLimit:t.savedForRetry);return false}catch{setOnline(false);setMsg(t.offlineSafe);return false}finally{syncing.current=false;setSaving(false)}
  }
  useEffect(()=>{syncLatest.current=()=>{void syncPending()}});
  async function nextHole(){
    const currentHole=hole;
    const complete=(data?.teams||[]).map(team=>({team,draft:currentDraft(team.id)})).filter(x=>x.draft?.openerId).map(x=>({teamId:x.team.id,hole:currentHole,openerId:x.draft!.openerId,strokes:x.draft!.strokes}));
    if(data&&complete.length)writePending(data.flight.id,complete);
    await syncPending(t.previousSaved);
    if(position===15){const completeRound=(data?.teams||[]).every(team=>Array.from({length:16},(_,i)=>i+1).every(holeNo=>draftFor(team.id,holeNo)?.openerId));if(completeRound)setShowResults(true);else setMsg(t.completeAll)}else setPosition(current=>current+1);
  }

  const languagePicker=<label className="languageSelect"><Languages size={16}/><span className="srOnly">{t.language}</span><select value={language} onChange={e=>switchLanguage(e.target.value as Language)} aria-label={t.language}><option value="hr">HR</option><option value="en">EN</option></select></label>;
  if(!data)return <main className="authPage green"><form className="loginCard" onSubmit={login}><div className="adminLoginTop"><Image src="/lagoda-logo.jpg" alt="Lagoda" width={82} height={68}/>{languagePicker}</div><span className="eyebrow">{t.recorder}</span><h1>{t.flightLogin}</h1><p>{t.loginIntro}</p><label>{t.flightCode}<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="R1-F01-4821" required/></label>{msg&&<div className="notice error">{msg}</div>}<button className="btn">{t.open}</button><Link href="/">{t.back}</Link></form></main>;

  return <main className="scorePage"><header className="scoreNav"><div className="brand light"><Image src="/lagoda-logo.jpg" alt="Lagoda" width={44} height={44}/><span>TEAM <b>SHOWDOWN</b></span></div><div><b>{data.flight.name}</b><span>{t.round} {data.flight.round_no}</span></div><span className={`sync ${!online||pendingCount?"offline":""}`}>{!online||pendingCount?<WifiOff/>:<Wifi/>} {saving?t.syncing:!online?`${pendingCount} ${t.local}`:pendingCount?`${pendingCount} ${t.waiting}`:"Online"}</span><div className="scoreLanguage">{languagePicker}</div></header>{showResults?<ResultsSummary data={data} draftFor={draftFor} language={language} onEdit={()=>{setPosition(0);setShowResults(false);setMsg("")}}/>:<section className="scoreShell"><div className="holeNav"><button onClick={()=>setPosition(current=>Math.max(0,current-1))} disabled={position===0} aria-label={t.previousHole}><ChevronLeft/></button><div><span>{t.hole}</span><b>{hole}</b><small>PAR {data.holes.find(h=>h.number===hole)?.par||3}</small></div><button onClick={nextHole} aria-label={position===15?t.finish:t.nextHole}><ChevronRight/></button></div>{msg&&<div className="notice">{msg}</div>}{data.teams.map(team=><ScoreTeam key={`${team.id}-${hole}`} team={team} current={currentDraft(team.id)} counts={openerCounts(team.id)} saved={data.scores.some(s=>s.team_id===team.id&&s.hole_no===hole)} onChange={value=>updateDraft(team.id,value)} language={language}/>) }<div className="scoreFoot"><button className="btn" onClick={nextHole}>{position===15?t.finish:t.nextHole} <ChevronRight/></button></div></section>}</main>;
}

function ResultsSummary({data,draftFor,language,onEdit}:{data:FlightData,draftFor:(teamId:string,hole:number)=>Draft|undefined,language:Language,onEdit:()=>void}){const t=copy[language],holeNumbers=Array.from({length:16},(_,i)=>i+1),coursePar=data.holes.reduce((sum,h)=>sum+h.par,0);return <section className="scoreResults"><div className="resultsHeading"><span className="eyebrow">{data.flight.name} · {t.round} {data.flight.round_no}</span><h1>{t.results}</h1><p>{t.resultsIntro}</p></div><div className="resultsTableWrap"><table><thead><tr><th>{t.team}</th>{holeNumbers.map(n=><th key={n}>{n}</th>)}<th>{t.total}</th><th>{t.toPar}</th></tr></thead><tbody>{data.teams.map(team=>{const values=holeNumbers.map(n=>draftFor(team.id,n)?.strokes),total=values.reduce<number>((sum,value)=>sum+(value||0),0),complete=values.every(Boolean),toPar=total-coursePar;return <tr key={team.id}><th>{team.name}</th>{values.map((value,i)=><td key={i}>{value||"—"}</td>)}<td><strong>{complete?total:"—"}</strong></td><td className={complete?(toPar<0?"under":toPar>0?"over":""):""}>{complete?(toPar>0?`+${toPar}`:toPar):"—"}</td></tr>})}</tbody></table></div><button className="btn" onClick={onEdit}>{t.editAgain}</button></section>}

function ScoreTeam({team,current,counts,saved,onChange,language}:{team:FlightData["teams"][0],current:Draft|undefined,counts:Record<string,number>,saved:boolean,onChange:(value:Draft)=>void,language:Language}){
  const t=copy[language];
  const [opener,setOpener]=useState(current?.openerId||""),[strokes,setStrokes]=useState(current?.strokes||3);
  function chooseOpener(id:string){if((counts[id]||0)>=4&&opener!==id)return;setOpener(id);onChange({openerId:id,strokes})}
  function changeStrokes(value:number){const next=Math.max(1,value);setStrokes(next);onChange({openerId:opener,strokes:next})}
  return <article className="scoreTeam"><div className="scoreTeamHead"><div><span>{t.team}</span><h2>{team.name}</h2></div>{saved&&<span className="saved"><Check/> {t.saved}</span>}</div><div className="fieldLabel">{t.opener}</div><div className="playerButtons">{team.players.map(p=>{const full=(counts[p.id]||0)>=4&&opener!==p.id;return <button onClick={()=>chooseOpener(p.id)} disabled={full} className={opener===p.id?"active":full?"limit":""} key={p.id}>{p.name}{full&&<small>4/4</small>}</button>})}</div><div className="fieldLabel">{t.strokes}</div><div className="strokePicker"><button onClick={()=>changeStrokes(strokes-1)}>−</button><b>{strokes}</b><button onClick={()=>changeStrokes(strokes+1)}>+</button></div><div className="openerSummary"><div className="fieldLabel">{t.openerRound}</div><div>{team.players.map(p=><span className={(counts[p.id]||0)>=4?"complete":""} key={p.id}><b>{p.name}</b><strong>{counts[p.id]||0}/4</strong></span>)}</div></div></article>;
}
