"use client";
import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { Check, ChevronLeft, ChevronRight, Wifi } from "lucide-react";

type FlightData={flight:{id:string,name:string,round_no:number,start_hole:number},teams:{id:string,name:string,players:{id:string,name:string}[]}[],scores:{team_id:string,hole_no:number,strokes:number,opener_id:string}[]};
export default function ScoringApp(){const [code,setCode]=useState(""),[data,setData]=useState<FlightData|null>(null),[hole,setHole]=useState(1),[msg,setMsg]=useState("");async function login(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/scoring",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"login",code})});if(r.ok){const d=await r.json();setData(d);setHole(d.flight.start_hole)}else setMsg("Šifra nije ispravna ili runda nije aktivna.")}
async function save(teamId:string,openerId:string,strokes:number){const r=await fetch("/api/scoring",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"score",teamId,hole,openerId,strokes})});if(r.ok){setMsg("Rezultat je spremljen.");const d=await r.json();setData(d)}else setMsg("Rezultat nije spremljen. Pokušajte ponovno.")}
if(!data)return <main className="authPage green"><form className="loginCard" onSubmit={login}><Image src="/lagoda-logo.jpg" alt="Lagoda" width={82} height={68}/><span className="eyebrow">ZAPISNIČAR</span><h1>Prijava flighta</h1><p>Unesite šifru koju ste dobili od organizatora.</p><label>Šifra flighta<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="R1-F01-4821" required/></label>{msg&&<div className="notice error">{msg}</div>}<button className="btn">Otvori scorecard</button><Link href="/">← Povratak na leaderboard</Link></form></main>;
return <main className="scorePage"><header className="scoreNav"><div className="brand light"><Image src="/lagoda-logo.jpg" alt="Lagoda" width={44} height={44}/><span>TEAM <b>SHOWDOWN</b></span></div><div><b>{data.flight.name}</b><span>Runda {data.flight.round_no}</span></div><span className="sync"><Wifi/> Online</span></header><section className="scoreShell"><div className="holeNav"><button onClick={()=>setHole(hole===1?16:hole-1)} aria-label="Prethodna staza"><ChevronLeft/></button><div><span>STAZA</span><b>{hole}</b><small>PAR 3</small></div><button onClick={()=>setHole(hole===16?1:hole+1)} aria-label="Sljedeća staza"><ChevronRight/></button></div>{msg&&<div className="notice">{msg}</div>}{data.teams.map(team=><ScoreTeam key={team.id} team={team} current={data.scores.find(s=>s.team_id===team.id&&s.hole_no===hole)} onSave={save}/>) }<div className="scoreFoot"><span>{data.scores.filter(s=>s.hole_no===hole).length}/{data.teams.length} rezultata uneseno</span><button className="btn" onClick={()=>setHole(hole===16?1:hole+1)}>Sljedeća staza <ChevronRight/></button></div></section></main>}
function ScoreTeam({team,current,onSave}:{team:FlightData["teams"][0],current:FlightData["scores"][0]|undefined,onSave:(t:string,o:string,s:number)=>void}){const [opener,setOpener]=useState(current?.opener_id||""),[strokes,setStrokes]=useState(current?.strokes||3);return <article className="scoreTeam"><div className="scoreTeamHead"><div><span>EKIPA</span><h2>{team.name}</h2></div>{current&&<span className="saved"><Check/> Spremljeno</span>}</div><div className="fieldLabel">Početno bacanje</div><div className="playerButtons">{team.players.map(p=><button onClick={()=>setOpener(p.id)} className={opener===p.id?"active":""} key={p.id}>{p.name}</button>)}</div><div className="fieldLabel">Broj bacanja</div><div className="strokePicker"><button onClick={()=>setStrokes(Math.max(1,strokes-1))}>−</button><b>{strokes}</b><button onClick={()=>setStrokes(strokes+1)}>+</button></div><button className="saveScore" disabled={!opener} onClick={()=>onSave(team.id,opener,strokes)}>{current?"Ažuriraj rezultat":"Spremi rezultat"}</button></article>}
