import { NextResponse } from "next/server";
import { isAdmin } from "@/lib/auth";
import { db } from "@/lib/supabase";

async function snapshot(){const client=db();if(!client)return {teams:[],flights:[],holes:[]};const [{data:teams},{data:flights},{data:holes}]=await Promise.all([client.from("teams").select("id,name,rating,players(id,name)").order("created_at"),client.from("flights").select("id,round_no,name,start_hole,access_code,flight_teams(teams(id,name))").order("round_no").order("name"),client.from("holes").select("number,par").order("number")]);return {teams:teams||[],flights:(flights||[]).map((f:any)=>({...f,teams:f.flight_teams.map((x:any)=>x.teams)})),holes:holes?.length?holes:Array.from({length:16},(_,i)=>({number:i+1,par:3}))}}
export async function GET(){if(!await isAdmin())return NextResponse.json({error:"unauthorized"},{status:401});return NextResponse.json(await snapshot())}
export async function POST(req:Request){if(!await isAdmin())return NextResponse.json({error:"unauthorized"},{status:401});const client=db();if(!client)return NextResponse.json({error:"database not configured"},{status:503});const body=await req.json();if(body.action==="team"){const name=String(body.name||"").trim(),players=Array.isArray(body.players)?body.players.map((p:unknown)=>String(p||"").trim()):[];if(!name||players.length!==4||players.some((p:string)=>!p))return NextResponse.json({error:"four players required"},{status:400});const {data:existing}=await client.from("teams").select("id").ilike("name",name).maybeSingle();if(existing)return NextResponse.json({error:"team already exists"},{status:409});const {data:team,error}=await client.from("teams").insert({name,rating:body.rating}).select().single();if(error)return NextResponse.json({error:error.message},{status:400});const {error:playerError}=await client.from("players").insert(players.map((playerName:string,sort_order:number)=>({team_id:team.id,name:playerName,sort_order})));if(playerError){await client.from("teams").delete().eq("id",team.id);return NextResponse.json({error:playerError.message},{status:400})}}
if(body.action==="deleteTeam"){const {data:team}=await client.from("teams").select("id,name").eq("id",body.teamId).single();if(!team||body.confirm!==team.name)return NextResponse.json({error:"confirmation required"},{status:400});const operations=[await client.from("audit_log").delete().eq("team_id",team.id),await client.from("hole_scores").delete().eq("team_id",team.id),await client.from("flight_teams").delete().eq("team_id",team.id),await client.from("teams").delete().eq("id",team.id)];const failed=operations.find(x=>x.error);if(failed?.error)return NextResponse.json({error:failed.error.message},{status:400})}
if(body.action==="generateFlights"){const round=Number(body.round);const {data:teams}=await client.from("teams").select("id").eq("active",true).order("created_at");if(!teams?.length)return NextResponse.json({error:"no teams"},{status:400});const {data:old}=await client.from("flights").select("id").eq("round_no",round);if(old?.length){await client.from("flight_teams").delete().in("flight_id",old.map(x=>x.id));await client.from("flights").delete().eq("round_no",round)}for(let i=0;i<teams.length;i+=2){const n=i/2+1,access=`R${round}-F${String(n).padStart(2,"0")}-${Math.floor(1000+Math.random()*9000)}`;const {data:f}=await client.from("flights").insert({round_no:round,name:`Flight ${n}`,start_hole:((n-1)*2)%16+1,access_code:access,active:true}).select().single();if(f)await client.from("flight_teams").insert(teams.slice(i,i+2).map((t,position)=>({flight_id:f.id,team_id:t.id,position})))}}
if(body.action==="startHole"){const start=Number(body.startHole);if(start<1||start>16)return NextResponse.json({error:"invalid hole"},{status:400});await client.from("flights").update({start_hole:start}).eq("id",body.flightId)}
if(body.action==="holes"){if(!Array.isArray(body.holes)||body.holes.length!==16||body.holes.some((h:any)=>h.number<1||h.number>16||h.par<1||h.par>9))return NextResponse.json({error:"invalid holes"},{status:400});const {error}=await client.from("holes").upsert(body.holes.map((h:any)=>({number:Number(h.number),par:Number(h.par),updated_at:new Date().toISOString()})));if(error)return NextResponse.json({error:error.message},{status:400})}
if(body.action==="resetTournament"){if(body.confirm!=="RESET")return NextResponse.json({error:"confirmation required"},{status:400});const operations=[await client.from("audit_log").delete().gt("id",0),await client.from("hole_scores").delete().neq("id","00000000-0000-0000-0000-000000000000"),await client.from("flight_teams").delete().neq("flight_id","00000000-0000-0000-0000-000000000000"),await client.from("flights").delete().neq("id","00000000-0000-0000-0000-000000000000")];const failed=operations.find(x=>x.error);if(failed?.error)return NextResponse.json({error:failed.error.message},{status:400})}
return NextResponse.json(await snapshot())}
