import { NextResponse } from "next/server";
import { isAdmin } from "@/lib/auth";
import { db } from "@/lib/supabase";

async function snapshot(){const client=db();if(!client)return {teams:[],flights:[]};const [{data:teams},{data:flights}]=await Promise.all([client.from("teams").select("id,name,rating,players(id,name)").order("created_at"),client.from("flights").select("id,round_no,name,start_hole,access_code,flight_teams(teams(id,name))").order("round_no").order("name")]);return {teams:teams||[],flights:(flights||[]).map((f:any)=>({...f,teams:f.flight_teams.map((x:any)=>x.teams)}))}}
export async function GET(){if(!await isAdmin())return NextResponse.json({error:"unauthorized"},{status:401});return NextResponse.json(await snapshot())}
export async function POST(req:Request){if(!await isAdmin())return NextResponse.json({error:"unauthorized"},{status:401});const client=db();if(!client)return NextResponse.json({error:"database not configured"},{status:503});const body=await req.json();if(body.action==="team"){if(!body.name||body.players?.length!==4)return NextResponse.json({error:"four players required"},{status:400});const {data:team,error}=await client.from("teams").insert({name:body.name,rating:body.rating}).select().single();if(error)return NextResponse.json({error:error.message},{status:400});await client.from("players").insert(body.players.map((name:string,sort_order:number)=>({team_id:team.id,name,sort_order})));}
if(body.action==="generateFlights"){const round=Number(body.round);const {data:teams}=await client.from("teams").select("id").eq("active",true).order("created_at");if(!teams?.length)return NextResponse.json({error:"no teams"},{status:400});const {data:old}=await client.from("flights").select("id").eq("round_no",round);if(old?.length){await client.from("flight_teams").delete().in("flight_id",old.map(x=>x.id));await client.from("flights").delete().eq("round_no",round)}for(let i=0;i<teams.length;i+=2){const n=i/2+1,access=`R${round}-F${String(n).padStart(2,"0")}-${Math.floor(1000+Math.random()*9000)}`;const {data:f}=await client.from("flights").insert({round_no:round,name:`Flight ${n}`,start_hole:((n-1)*2)%16+1,access_code:access,active:true}).select().single();if(f)await client.from("flight_teams").insert(teams.slice(i,i+2).map((t,position)=>({flight_id:f.id,team_id:t.id,position})))}}
if(body.action==="startHole"){const start=Number(body.startHole);if(start<1||start>16)return NextResponse.json({error:"invalid hole"},{status:400});await client.from("flights").update({start_hole:start}).eq("id",body.flightId)}
return NextResponse.json(await snapshot())}
